spring:
  datasource:
    url: jdbc:mysql://localhost:3306/GestioneAcquistiVendite?useSSL=false
    username: asmaa
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


server:
  port: 9500
  servlet:
    context-path: /api


