spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:mysql://localhost:3306/GestioneAcquistiVendite?useSSL=false
    username: asmaa
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    serialization:
      fail-on-empty-beans: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  batch:
    jdbc:
      initialize-schema: always

server:
  port: 9500
  servlet:
    context-path: /api
export:
  file:
    path: /path/to/export/file.csv
